packages:
  - "packages/*"
  - "apps/*"

overrides:
  lit: "^3.3.1"

allowBuilds:
  esbuild: true
  rs-module-lexer: true
  sharp: true
  simple-git-hooks: true

linkWorkspacePackages: true
preferWorkspacePackages: true
saveWorkspaceProtocol: false
