packages:
  - "packages/*"
  - "apps/*"

minimumReleaseAge: 1440
blockExoticSubdeps: true
trustPolicy: no-downgrade

allowBuilds:
  esbuild: true
  rs-module-lexer: true
  sharp: true
  simple-git-hooks: true

linkWorkspacePackages: true
preferWorkspacePackages: true
saveWorkspaceProtocol: false
