name: Create Beta Release

on:
  push:
    branches:
      - beta
      - refactor/web-components

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        name: Create release PR
        with:
          release-type: node
          prerelease: true
          target-branch: ${{ github.ref_name }}

      - uses: actions/checkout@v4
        name: Checkout code
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}

      - run: npm test
        name: Run tests
        if: ${{ steps.release.outputs.release_created }}

      - run: npm run build
        name: Run build
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish --tag beta
        name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
